import type { Product } from "@/lib/types";

// Geçici yer tutucu veri. Supabase + Prisma bağlanınca bu dosya silinir,
// sorgular src/server/products.ts üzerinden gerçek DB'ye gider.
// Görseller: public/placeholders/*.svg (temsili). 2. el gerçek ilanlarda AI görsel yok.

function img(type: string, n: number, title: string) {
  return {
    url: `/placeholders/${type}-${String(n).padStart(2, "0")}.svg`,
    alt: `${title} — temsili görsel`,
    isCover: true,
  };
}

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p-mtb-1",
    slug: "trailblaze-hardtail-dag-bisikleti",
    title: "Trailblaze Hardtail Dağ Bisikleti",
    description:
      "Hafif alüminyum kadro, hidrolik disk fren ve 29 jant ile patika ve şehir dışı sürüşler için ideal hardtail dağ bisikleti.",
    brand: "Trailblaze",
    condition: "NEW",
    sellerType: "SHOP",
    bikeType: "MOUNTAIN",
    frameSize: "L",
    wheelSize: 29,
    gearCount: 21,
    brakeType: "Disk (Hidrolik)",
    color: "Mat Yeşil",
    priceCents: 1849000,
    compareAtCents: 2100000,
    stock: 6,
    usageLevel: null,
    manufactureYear: null,
    cosmeticNotes: null,
    mileageKm: null,
    images: [img("mountain", 1, "Dağ bisikleti")],
    specs: [
      { key: "Kadro Malzemesi", value: "Alüminyum 6061" },
      { key: "Amortisör", value: "Ön 100mm" },
      { key: "Vites Sistemi", value: "Shimano Altus" },
    ],
    isPlaceholder: true,
    createdAt: "2026-06-20T10:00:00Z",
  },
  {
    id: "p-road-1",
    slug: "aerolite-yol-yaris-bisikleti",
    title: "Aerolite Yol Yarış Bisikleti",
    description:
      "Aerodinamik karbon kadro, drop gidon ve ince slick lastiklerle asfaltta yüksek hız için tasarlanmış yol bisikleti.",
    brand: "Aerolite",
    condition: "NEW",
    sellerType: "SHOP",
    bikeType: "ROAD",
    frameSize: "M",
    wheelSize: 28,
    gearCount: 22,
    brakeType: "Disk (Mekanik)",
    color: "Kırmızı",
    priceCents: 3299000,
    compareAtCents: null,
    stock: 3,
    usageLevel: null,
    manufactureYear: null,
    cosmeticNotes: null,
    mileageKm: null,
    images: [img("road", 1, "Yol bisikleti")],
    specs: [
      { key: "Kadro Malzemesi", value: "Karbon" },
      { key: "Vites Sistemi", value: "Shimano 105" },
    ],
    isPlaceholder: true,
    createdAt: "2026-06-22T10:00:00Z",
  },
  {
    id: "p-city-1",
    slug: "urban-cruise-sehir-bisikleti",
    title: "Urban Cruise Şehir Bisikleti",
    description:
      "Dik sürüş pozisyonu, çamurluk ve arka taşıyıcı ile günlük şehir içi ulaşım için konforlu step-through şehir bisikleti.",
    brand: "Urban",
    condition: "NEW",
    sellerType: "SHOP",
    bikeType: "CITY",
    frameSize: "M",
    wheelSize: 28,
    gearCount: 7,
    brakeType: "V-Brake",
    color: "Krem",
    priceCents: 1249000,
    compareAtCents: 1450000,
    stock: 10,
    usageLevel: null,
    manufactureYear: null,
    cosmeticNotes: null,
    mileageKm: null,
    images: [img("city", 1, "Şehir bisikleti")],
    specs: [
      { key: "Kadro Malzemesi", value: "Çelik" },
      { key: "Ekstra", value: "Çamurluk + Arka taşıyıcı" },
    ],
    isPlaceholder: true,
    createdAt: "2026-06-25T10:00:00Z",
  },
  {
    id: "p-ebike-1",
    slug: "voltride-elektrikli-sehir-bisikleti",
    title: "VoltRide Elektrikli Şehir Bisikleti",
    description:
      "Kadroya entegre batarya ve arka göbek motoru ile 60 km menzilli, sessiz ve güçlü elektrikli şehir bisikleti.",
    brand: "VoltRide",
    condition: "NEW",
    sellerType: "SHOP",
    bikeType: "ELECTRIC",
    frameSize: "L",
    wheelSize: 27.5,
    gearCount: 8,
    brakeType: "Disk (Hidrolik)",
    color: "Gri",
    priceCents: 4499000,
    compareAtCents: 4999000,
    stock: 4,
    usageLevel: null,
    manufactureYear: null,
    cosmeticNotes: null,
    mileageKm: null,
    images: [img("electric", 1, "Elektrikli bisiklet")],
    specs: [
      { key: "Batarya", value: "36V 14Ah" },
      { key: "Menzil", value: "~60 km" },
      { key: "Motor", value: "250W arka göbek" },
    ],
    isPlaceholder: true,
    createdAt: "2026-06-27T10:00:00Z",
  },
  {
    id: "p-kids-1",
    slug: "minirider-cocuk-bisikleti-16",
    title: "MiniRider Çocuk Bisikleti 16''",
    description:
      "Yan tekerlekli, 16 inç jantlı, canlı mavi kadrolu, 4-6 yaş çocuklar için güvenli ve hafif bisiklet.",
    brand: "MiniRider",
    condition: "NEW",
    sellerType: "SHOP",
    bikeType: "KIDS",
    frameSize: "XS",
    wheelSize: 16,
    gearCount: 1,
    brakeType: "V-Brake",
    color: "Mavi",
    priceCents: 429000,
    compareAtCents: null,
    stock: 15,
    usageLevel: null,
    manufactureYear: null,
    cosmeticNotes: null,
    mileageKm: null,
    images: [img("kids", 1, "Çocuk bisikleti")],
    specs: [
      { key: "Yaş", value: "4-6 yaş" },
      { key: "Ekstra", value: "Yan tekerlek dahil" },
    ],
    isPlaceholder: true,
    createdAt: "2026-06-28T10:00:00Z",
  },
  {
    id: "p-gravel-1",
    slug: "pathfinder-gravel-bisikleti",
    title: "Pathfinder Gravel Macera Bisikleti",
    description:
      "Drop gidon, geniş tan-wall lastikler ve sağlam kadro ile hem asfaltta hem toprak yolda keyifli gravel bisikleti.",
    brand: "Pathfinder",
    condition: "NEW",
    sellerType: "SHOP",
    bikeType: "GRAVEL",
    frameSize: "M",
    wheelSize: 28,
    gearCount: 18,
    brakeType: "Disk (Hidrolik)",
    color: "Kum",
    priceCents: 2749000,
    compareAtCents: null,
    stock: 5,
    usageLevel: null,
    manufactureYear: null,
    cosmeticNotes: null,
    mileageKm: null,
    images: [img("gravel", 1, "Gravel bisikleti")],
    specs: [
      { key: "Kadro Malzemesi", value: "Alüminyum" },
      { key: "Lastik", value: "700x40c tan-wall" },
    ],
    isPlaceholder: true,
    createdAt: "2026-06-29T10:00:00Z",
  },
  // ---- 2. EL (USED) örnekleri ----
  {
    id: "p-used-mtb-1",
    slug: "ikinci-el-rockline-dag-bisikleti",
    title: "Rockline Dağ Bisikleti (2. El)",
    description:
      "Az kullanılmış, bakımlı dağ bisikleti. Dükkanımız tarafından kontrol edildi, ekspertiz raporu mevcut.",
    brand: "Rockline",
    condition: "USED",
    sellerType: "SHOP",
    bikeType: "MOUNTAIN",
    frameSize: "M",
    wheelSize: 27.5,
    gearCount: 24,
    brakeType: "Disk (Mekanik)",
    color: "Siyah",
    priceCents: 899000,
    compareAtCents: 1250000,
    stock: 1,
    usageLevel: "Az Kullanılmış",
    manufactureYear: 2023,
    cosmeticNotes: "Sol pedal kolunda hafif çizik, mekanik olarak sorunsuz.",
    mileageKm: 850,
    images: [img("mountain", 2, "2. el dağ bisikleti")],
    specs: [
      { key: "Kadro Malzemesi", value: "Alüminyum" },
      { key: "Kontrol", value: "Dükkan ekspertizi yapıldı" },
    ],
    isPlaceholder: true,
    createdAt: "2026-06-26T10:00:00Z",
  },
  {
    id: "p-used-city-1",
    slug: "ikinci-el-urban-classic-sehir-bisikleti",
    title: "Urban Classic Şehir Bisikleti (2. El)",
    description:
      "İyi durumda, günlük kullanıma hazır şehir bisikleti. Yeni lastik takıldı, frenler ayarlandı.",
    brand: "Urban",
    condition: "USED",
    sellerType: "SHOP",
    bikeType: "CITY",
    frameSize: "L",
    wheelSize: 28,
    gearCount: 3,
    brakeType: "V-Brake",
    color: "Lacivert",
    priceCents: 549000,
    compareAtCents: null,
    stock: 1,
    usageLevel: "İyi",
    manufactureYear: 2021,
    cosmeticNotes: "Selede hafif solma, genel durumu iyi.",
    mileageKm: null,
    images: [img("city", 2, "2. el şehir bisikleti")],
    specs: [{ key: "Kontrol", value: "Dükkan ekspertizi yapıldı" }],
    isPlaceholder: true,
    createdAt: "2026-06-24T10:00:00Z",
  },
];
